"""init schema

Revision ID: a4730d017c1d
Revises: 
Create Date: 2026-03-04 20:04:04.717536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4730d017c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_photos_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_photos_is_main'), ['is_main'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=30), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('useful_life_days', sa.Integer(), nullable=True),
    sa.Column('useful_life_months', sa.Integer(), nullable=True),
    sa.Column('depreciation_method', sa.String(length=30), nullable=True),
    sa.Column('rent_day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rent_month', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rent_year', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('main_photo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['main_photo_id'], ['asset_photos.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_code'), ['asset_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_unit_id'), ['unit_id'], unique=False)

    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_brands_name')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_categories_code')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('ship_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('rent_price_per_day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_suppliers_name')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_units_name')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_name'), ['name'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_no', sa.String(length=30), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_date'), ['po_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_no'), ['po_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=30), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rent_start', sa.Date(), nullable=True),
    sa.Column('rent_end', sa.Date(), nullable=True),
    sa.Column('project_site', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vat_mode', sa.String(length=20), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('wht_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wht_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_incl_vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_payable', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_extra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotes_status'), ['status'], unique=False)

    op.create_table('stock_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_date', sa.DateTime(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_no', sa.String(length=50), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('qty_in', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('qty_out', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_moves_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_moves_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_moves_move_date'), ['move_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_moves_ref_no'), ['ref_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_moves_ref_type'), ['ref_type'], unique=False)

    op.create_table('grns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_no', sa.String(length=30), nullable=False),
    sa.Column('grn_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assets_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grns_assets_generated_at'), ['assets_generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grns_grn_date'), ['grn_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_grns_grn_no'), ['grn_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_grns_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_grns_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('qty_received_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('receive_status', sa.String(length=20), server_default='OPEN', nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_receive_status'), ['receive_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_unit_id'), ['unit_id'], unique=False)

    op.create_table('quote_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_lines_quote_id'), ['quote_id'], unique=False)

    op.create_table('rental_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=30), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('project_site', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_contracts_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_rental_contracts_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_contracts_status'), ['status'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=30), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_doc_date'), ['doc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_status'), ['status'], unique=False)

    op.create_table('grn_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('qty_received', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grn_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_lines_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_lines_grn_id'), ['grn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_lines_po_line_id'), ['po_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_lines_unit_id'), ['unit_id'], unique=False)

    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_note', sa.Text(), nullable=True),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['rental_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installments_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installments_status'), ['status'], unique=False)

    op.create_table('rental_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('doc_no', sa.String(length=30), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rent_start', sa.Date(), nullable=True),
    sa.Column('rent_end', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_orders_doc_date'), ['doc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_orders_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_rental_orders_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_orders_status'), ['status'], unique=False)

    op.create_table('reservation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('quote_line_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('qty_requested', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_lines_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_lines_quote_line_id'), ['quote_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_lines_reservation_id'), ['reservation_id'], unique=False)

    op.create_table('billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=30), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billings_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_billings_installment_id'), ['installment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_billings_status'), ['status'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=30), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_receipts_installment_id'), ['installment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_receipts_status'), ['status'], unique=False)

    op.create_table('rental_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_order_id', sa.Integer(), nullable=False),
    sa.Column('reservation_line_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), server_default='1.00', nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['rental_order_id'], ['rental_orders.id'], ),
    sa.ForeignKeyConstraint(['reservation_line_id'], ['reservation_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_lines_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_lines_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_lines_rental_order_id'), ['rental_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_lines_reservation_line_id'), ['reservation_line_id'], unique=False)

    op.create_table('repair_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_order_id', sa.Integer(), nullable=True),
    sa.Column('doc_no', sa.String(length=30), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rental_order_id'], ['rental_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_orders_doc_date'), ['doc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_orders_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_repair_orders_rental_order_id'), ['rental_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_orders_status'), ['status'], unique=False)

    op.create_table('reservation_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_line_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['reservation_line_id'], ['reservation_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_assets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_assets_locked_at'), ['locked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_assets_released_at'), ['released_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_assets_reservation_line_id'), ['reservation_line_id'], unique=False)

    op.create_table('tax_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=30), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_invoices_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_tax_invoices_installment_id'), ['installment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tax_invoices_status'), ['status'], unique=False)

    op.create_table('repair_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_order_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_lines_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_lines_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_lines_repair_order_id'), ['repair_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_lines_repair_order_id'))
        batch_op.drop_index(batch_op.f('ix_repair_lines_category_id'))
        batch_op.drop_index(batch_op.f('ix_repair_lines_asset_id'))

    op.drop_table('repair_lines')
    with op.batch_alter_table('tax_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_tax_invoices_installment_id'))
        batch_op.drop_index(batch_op.f('ix_tax_invoices_doc_no'))

    op.drop_table('tax_invoices')
    with op.batch_alter_table('reservation_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_assets_reservation_line_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_assets_released_at'))
        batch_op.drop_index(batch_op.f('ix_reservation_assets_locked_at'))
        batch_op.drop_index(batch_op.f('ix_reservation_assets_asset_id'))

    op.drop_table('reservation_assets')
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_orders_status'))
        batch_op.drop_index(batch_op.f('ix_repair_orders_rental_order_id'))
        batch_op.drop_index(batch_op.f('ix_repair_orders_doc_no'))
        batch_op.drop_index(batch_op.f('ix_repair_orders_doc_date'))

    op.drop_table('repair_orders')
    with op.batch_alter_table('rental_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_lines_reservation_line_id'))
        batch_op.drop_index(batch_op.f('ix_rental_lines_rental_order_id'))
        batch_op.drop_index(batch_op.f('ix_rental_lines_category_id'))
        batch_op.drop_index(batch_op.f('ix_rental_lines_asset_id'))

    op.drop_table('rental_lines')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_status'))
        batch_op.drop_index(batch_op.f('ix_receipts_installment_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_doc_no'))

    op.drop_table('receipts')
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billings_status'))
        batch_op.drop_index(batch_op.f('ix_billings_installment_id'))
        batch_op.drop_index(batch_op.f('ix_billings_doc_no'))

    op.drop_table('billings')
    with op.batch_alter_table('reservation_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_lines_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_lines_quote_line_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_lines_category_id'))

    op.drop_table('reservation_lines')
    with op.batch_alter_table('rental_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_orders_status'))
        batch_op.drop_index(batch_op.f('ix_rental_orders_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_rental_orders_doc_no'))
        batch_op.drop_index(batch_op.f('ix_rental_orders_doc_date'))

    op.drop_table('rental_orders')
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installments_status'))
        batch_op.drop_index(batch_op.f('ix_installments_contract_id'))

    op.drop_table('installments')
    with op.batch_alter_table('grn_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_lines_unit_id'))
        batch_op.drop_index(batch_op.f('ix_grn_lines_po_line_id'))
        batch_op.drop_index(batch_op.f('ix_grn_lines_grn_id'))
        batch_op.drop_index(batch_op.f('ix_grn_lines_category_id'))

    op.drop_table('grn_lines')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_reservations_quote_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_reservations_doc_no'))
        batch_op.drop_index(batch_op.f('ix_reservations_doc_date'))

    op.drop_table('reservations')
    with op.batch_alter_table('rental_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_rental_contracts_quote_id'))
        batch_op.drop_index(batch_op.f('ix_rental_contracts_doc_no'))

    op.drop_table('rental_contracts')
    with op.batch_alter_table('quote_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_lines_quote_id'))

    op.drop_table('quote_lines')
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_unit_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_receive_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_po_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_category_id'))

    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('grns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grns_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_grns_status'))
        batch_op.drop_index(batch_op.f('ix_grns_po_id'))
        batch_op.drop_index(batch_op.f('ix_grns_grn_no'))
        batch_op.drop_index(batch_op.f('ix_grns_grn_date'))
        batch_op.drop_index(batch_op.f('ix_grns_assets_generated_at'))

    op.drop_table('grns')
    with op.batch_alter_table('stock_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_moves_ref_type'))
        batch_op.drop_index(batch_op.f('ix_stock_moves_ref_no'))
        batch_op.drop_index(batch_op.f('ix_stock_moves_move_date'))
        batch_op.drop_index(batch_op.f('ix_stock_moves_category_id'))
        batch_op.drop_index(batch_op.f('ix_stock_moves_asset_id'))

    op.drop_table('stock_moves')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_status'))
        batch_op.drop_index(batch_op.f('ix_quotes_doc_no'))

    op.drop_table('quotes')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_no'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_date'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_name'))
        batch_op.drop_index(batch_op.f('ix_units_is_active'))

    op.drop_table('units')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_is_active'))

    op.drop_table('suppliers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_name'))

    op.drop_table('products')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_code'))

    op.drop_table('customers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_categories_code'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))
        batch_op.drop_index(batch_op.f('ix_brands_is_active'))

    op.drop_table('brands')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_unit_id'))
        batch_op.drop_index(batch_op.f('ix_assets_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_assets_name'))
        batch_op.drop_index(batch_op.f('ix_assets_category_id'))
        batch_op.drop_index(batch_op.f('ix_assets_brand_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_code'))

    op.drop_table('assets')
    with op.batch_alter_table('asset_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_photos_is_main'))
        batch_op.drop_index(batch_op.f('ix_asset_photos_asset_id'))

    op.drop_table('asset_photos')
    # ### end Alembic commands ###
